version: '3'

services:
  mariadb:
    container_name: "mariadb"
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    restart: on-failure
    networks:
      - wordpress-mariadb
    ports:
      - 3306:3306
    volumes:
      - mariadb-volume:/var/lib/mysql
    env_file:
      - .env

  wordpress:
    container_name: "wordpress"
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - mariadb
    networks:
      - nginx-wordpress
      - wordpress-mariadb
    ports:
      - 9000:9000
    volumes:
      - wordpress-volume:/var/www/html
    env_file:
      - .env

  nginx:
    container_name: "nginx"
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - mariadb
      - wordpress
    ports:
      - 443:443
    restart: on-failure
    networks:
      - nginx-wordpress
    volumes:
      - wordpress-volume:/var/www/html
    env_file:
      - .env
      
networks:
  nginx-wordpress:
    driver: bridge
  wordpress-mariadb:
    driver: bridge

volumes:
  mariadb-volume:
  wordpress-volume:
